version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run: docker-compose ps
      - run: docker-compose exec db mysqladmin ping -u user -ppassword
      - run: docker-compose exec app php artisan key:generate --env=testing
      - run: cat server/.env.testing
      - run:
          name: migrate
          command: docker-compose exec app php artisan migrate --env=testing
      - run:
          name: test
          command: docker-compose exec app vendor/bin/phpunit
      - run:
          name: docker-compose down
          command: docker-compose down
