version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
        name: docker-compose up
        commnad: docker-compose up -d
      - run:
        name: migrate
        commnad: docker-compose exec app php artisan migrate
      - run:
        name: test
        commnad: docker-compose exec app vendor/bin/phpunit
      - run:
        name: docker-compose down
        commnad: docker-compose down
