version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
      environment:
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: migrate
          command: docker-compose exec app php artisan migrate --force --env=testing
      - run:
          name: test
          command: docker-compose exec app vendor/bin/phpunit
      - run:
          name: docker-compose down
          command: docker-compose down
